"""
Update stock quotes for the AI supply-chain webpage.

How it works:
1. Reads index.html.
2. Extracts every TradingView stock link in the page.
3. Converts TradingView symbols to yfinance tickers.
4. Downloads recent daily prices.
5. Writes quotes.json for the webpage to load.

Supported TradingView exchanges:
TWSE -> .TW
TPEX -> .TWO
NASDAQ / NYSE -> US tickers
TSE -> .T
KRX -> .KS
"""

import json
import re
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import pandas as pd
import yfinance as yf


HTML_FILE = Path("index.html")
OUTPUT_FILE = Path("quotes.json")

EXCHANGE_SUFFIX = {
    "TWSE": ".TW",
    "TPEX": ".TWO",
    "NASDAQ": "",
    "NYSE": "",
    "TSE": ".T",
    "KRX": ".KS",
}


def tradingview_to_yfinance(tv_symbol: str):
    tv_symbol = tv_symbol.strip().upper()
    if "-" not in tv_symbol:
        return None, None, None

    exchange, symbol = tv_symbol.split("-", 1)
    if exchange not in EXCHANGE_SUFFIX:
        return exchange, symbol, None

    return exchange, symbol, symbol + EXCHANGE_SUFFIX[exchange]


def extract_symbols_from_html(html_path: Path):
    html = html_path.read_text(encoding="utf-8")

    pattern = re.compile(
        r"https://www\.tradingview\.com/symbols/([^\"'/]+)/?",
        re.IGNORECASE,
    )

    symbols = {}

    for match in pattern.finditer(html):
        tv_symbol = match.group(1)
        exchange, code, yf_ticker = tradingview_to_yfinance(tv_symbol)

        if not yf_ticker:
            continue

        symbols[code] = {
            "exchange": exchange,
            "tradingview": tv_symbol.upper(),
            "yfinance": yf_ticker,
        }

    return symbols


def to_float(value):
    if isinstance(value, pd.Series):
        return float(value.iloc[0])
    return float(value)


def format_price(value: float, ticker: str):
    # US, Japan, Korea, Taiwan all display cleanly with this rule.
    if value >= 100:
        return f"{value:,.0f}"
    return f"{value:,.2f}".rstrip("0").rstrip(".")


def fetch_quote(yf_ticker: str):
    df = yf.download(
        yf_ticker,
        period="10d",
        interval="1d",
        progress=False,
        auto_adjust=False,
        threads=False,
    )

    if df is None or df.empty:
        raise ValueError("empty dataframe")

    close_series = df["Close"].dropna()

    if len(close_series) < 2:
        raise ValueError("less than two close prices")

    close = to_float(close_series.iloc[-1])
    prev_close = to_float(close_series.iloc[-2])

    if prev_close == 0:
        raise ValueError("previous close is zero")

    change_pct = (close / prev_close - 1) * 100

    return {
        "close": format_price(close, yf_ticker),
        "change_pct": f"{change_pct:+.2f}%",
    }


def main():
    if not HTML_FILE.exists():
        raise FileNotFoundError("index.html not found. Put this script beside index.html.")

    symbols = extract_symbols_from_html(HTML_FILE)

    quotes = {
        "_updated_at": datetime.now(ZoneInfo("Asia/Taipei")).strftime("%Y/%m/%d"),
        "_source": "Generated by update_quotes.py from TradingView links in index.html",
        "_count": len(symbols),
    }

    failed = {}

    print(f"Found {len(symbols)} symbols in index.html")

    for code, meta in sorted(symbols.items()):
        yf_ticker = meta["yfinance"]

        try:
            q = fetch_quote(yf_ticker)
            quotes[code] = {
                **q,
                "ticker": yf_ticker,
                "tradingview": meta["tradingview"],
            }
            print(f"OK     {code:>8} {yf_ticker:<12} {q['close']:>10} {q['change_pct']:>8}")

        except Exception as exc:
            failed[code] = {
                "ticker": yf_ticker,
                "tradingview": meta["tradingview"],
                "error": str(exc),
            }
            print(f"FAILED {code:>8} {yf_ticker:<12} {exc}")

        time.sleep(0.25)

    quotes["_failed"] = failed

    OUTPUT_FILE.write_text(
        json.dumps(quotes, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"Saved {OUTPUT_FILE}")
    print(f"Success: {len(quotes) - 4}, Failed: {len(failed)}")


if __name__ == "__main__":
    main()
